// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV8K-cxDOQhi0ArYZtVU4y-C1idL4SGno',
    appId: '1:766219053391:web:3f42abacd7c5f9f4047d3a',
    messagingSenderId: '766219053391',
    projectId: 'portfolio-8e095',
    authDomain: 'portfolio-8e095.firebaseapp.com',
    storageBucket: 'portfolio-8e095.firebasestorage.app',
    measurementId: 'G-TFH4VGBG48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhOu3tdONNLnebu_6g4DINslvTjvHlTs',
    appId: '1:766219053391:android:6b0b75dc1272c11b047d3a',
    messagingSenderId: '766219053391',
    projectId: 'portfolio-8e095',
    storageBucket: 'portfolio-8e095.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowElBbb34Sdu-HlF22ITS8wkn2eQ_PH4',
    appId: '1:766219053391:ios:bc0da617583683ed047d3a',
    messagingSenderId: '766219053391',
    projectId: 'portfolio-8e095',
    storageBucket: 'portfolio-8e095.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowElBbb34Sdu-HlF22ITS8wkn2eQ_PH4',
    appId: '1:766219053391:ios:bc0da617583683ed047d3a',
    messagingSenderId: '766219053391',
    projectId: 'portfolio-8e095',
    storageBucket: 'portfolio-8e095.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV8K-cxDOQhi0ArYZtVU4y-C1idL4SGno',
    appId: '1:766219053391:web:f38a5a201df5f24f047d3a',
    messagingSenderId: '766219053391',
    projectId: 'portfolio-8e095',
    authDomain: 'portfolio-8e095.firebaseapp.com',
    storageBucket: 'portfolio-8e095.firebasestorage.app',
    measurementId: 'G-43C2KZ7111',
  );
}
